* table

** 参考文档

  - https://liam.page/2013/08/04/LaTeX-table/

** 普通table

\begin{tabular}{cc}
我是& 一只\\
表格君& 咿呀咿呀哟
\end{tabular}


*** 普通table 加上 hline

\begin{tabular}{|l|r|}
\hline
我是& 一只\\
\hline
表格君& 咿呀咿呀哟\\
\hline
\end{tabular}

*** 三线表

科技论文写作中，更常见的可能是三线表

\begin{tabular}{ccc}
\hline
姓名& 学号& 性别\\
\hline
Ch'en Meng& 001& Male\\
Sarah Brightman& 002& Female\\
\hline
\end{tabular}


*** 更为美观

通常来说，我们会希望表格的第一根线和最后一根线比表格中的横线更粗一些。booktabs 宏包为我们提供了这个功能，加载 booktabs 宏包之后我们可以使用 toprule 和  bottomrule 命令分别画出表格头和表格底的粗横线，而用 midrule 画出表格中的横线。

\begin{tabular}{ccc}
\toprule
姓名& 学号& 性别\\
\midrule
Ch'en Meng& 001& Male\\
Sarah Brightman& 002& Female\\
\bottomrule
\end{tabular}


** table环境

LaTeX 的排版的一个特点就是编号和位置浮动的自动化。为了让表格能够自动编号并尽可能美观的浮动，LaTeX 提供了 table 环境。基本用法如下

\begin{table}[!htbp]
\centering
\caption{代码06的表格}\label{tab:aStrangeTable}
\begin{tabular}{ccc}
\toprule
姓名& 学号& 性别\\
\midrule
Ch'en Meng& 001& Male\\
Sarah Brightman& 002& Female\\
\bottomrule
\end{tabular}
\end{table}

注意到 table 环境后面跟了一些由方括号包括起来的可选参数 [!htbp].

  - 其中 h 代表 here, 意思是将表格排在当前文字的位置

  - t 表示将表格放在下一页的 top (页首)；

  - b 表示将表格放在当前页的 bottom (底部)

  - p 表示表格单独放在一个浮动页中

  - 最前面的 ! 表示忽略美观因素，尽可能按照参数指定的方式来处理表格浮动位置。

因此这五个参数放在一起就表示「尽可能将表格放在这里，不行就放在下一页的页首，再不行就放在这一页的底部，如果实在不行就单独成页吧」。


** 跨行和跨列的表格

在 tabular 中，可以用 multicolumn{cols}{pos}{text} 来使得 text 占据 cols 个 cells, 并遵照 pos 中指示的位置。其中 pos 中支持竖线 | 的使用，以在合并后的 cells 两侧绘制竖线。

学生信息这行点了三个col


\begin{table}[!htbp]
\centering
\caption{代码07的表格}\label{tab:aStrangeTable}
\begin{tabular}{|c|c|c|}
\hline
\multicolumn{3}{|c|}{学生信息}\\
\hline
姓名& 学号& 性别\\
\hline
Ch'en Meng& 001& Male\\
Sarah Brightman& 002& Female\\
\hline
\end{tabular}
\end{table}

注意如果横向合并 cells 之后，改行的列数会相应增加。亦即在上述例子中，第一行的 cell 占据了 3 列的空间，如果在其后添加 & 符号（表示希望将接下来的内容添加在下一列），则会提示列数过多。


*** 纵向合并

纵向合并 cells 需要 multirow 宏包的支持。该宏包提供的 multirow{rows}{width}{text} 命令能够实现我们的需求。其中若 width 参数中填入 *, 则占据的宽度会根据需要自动增减。


\begin{table}[!htbp]
\centering
\caption{代码08的表格}\label{tab:aStrangeTable}
\begin{tabular}{|c|c|c|c|}
\hline
\multicolumn{4}{|c|}{学生信息}\\
\hline
班级& 姓名& 学号& 性别\\
\hline
\multirow{2}*{1 班}& Ch'en Meng& 001& Male\\
& Sarah Brightman& 002& Female\\
\hline
\end{tabular}
\end{table}

注意该命令仅仅是将目标位置的 text 扩展到了包括目标位置所在的 rows 行。因此，在其下的若干行，必须用 & 符号空出相应的位置，不然就会导致文字重叠。例如编译下面的代码

=Sarah Brightman= 前少了一个 =&= 符号


\begin{table}[!htbp]
\centering
\caption{这是一张奇怪的表格}\label{tab:aStrangeTable}
\begin{tabular}{|c|c|c|c|}
\hline
\multicolumn{4}{|c|}{学生信息}\\
\hline
班级                     & 姓名              & 学号        & 性别\\
\hline
\multirow{2}*{1 班}      & Ch'en Meng        & 001         & Male\\
                         Sarah Brightman     & 002         & Female\\
\hline
\end{tabular}
\end{table}


*** 既跨行又跨列

显见，实现这样的需求需要将上述两个命令结合起来使用。但是只能用 multicolumn{cols}{pos}{multirow{rows}{width}{text}} 这样的形式，而不能反过来嵌套。具体原因不明。

代码09


\begin{tabular}{|*{10}{r|}}
\hline
\multicolumn{2}{|c|}{\multirow{2}*{Blank}}
& \multicolumn{2}{|c|}{CG} & \multicolumn{2}{|c|}{IS}
& \multicolumn{2}{|c|}{MG} & \multicolumn{2}{|c|}{LU}\\\cline{3-10}
\multicolumn{2}{|c|}{}  & 2   & 4 & 2 & 4 & 2 & 4 & 2 & 4\\\hline
\multirow{2}*{Run Time(s)}
& IA32 & 24.37   & 16.18 & 19.62 & 8.98 & 31.98 & 18.71 & 622.76 & 266.16\\
& IA64 & 54.41   & 30.29 & 25.54 & 15.72 & 164.16 & 84.73 & 3226.60 & 1723.11\\\hline
\multirow{2}*{Sync Time(ms)}
& IA32 & 7.156   & 25.607 & 189.793 & 70.336 & 286.354 & 86.888 & 6.446 & 18.434\\
& IA64 & 5.960   & 7.043 & 21.980 & 10.078 & 2.780 & 13.793& 2.922 & 5.385\\\hline
\end{tabular}


** 体型“不正常”的表格


*** “肥胖”表格

你可能已经注意到，在代码 09 中，我使用了 standalone 文档类，而不是之前一直在使用的 ctexart 文档类。standalone 这个文档类，会根据需要，设定恰好的纸张大小，特别适合生成 pdf 格式的图档。事实上，在代码 09 中的表格，就是一个「肥胖」的表格。如果你把上面这段代码放在普通的 article 文档类中，或是像之前一样放在 ctexart 中，因为表格过于宽，会超过页面跑到异次元去。比如你可以编译下面的代码试试看

% 我是一个错误演示
\documentclass{article}
\usepackage{multirow}
\begin{document}
\begin{tabular}{|*{10}{r|}}
\hline
\multicolumn{2}{|c|}{\multirow{2}*{Blank}}
& \multicolumn{2}{|c|}{CG} & \multicolumn{2}{|c|}{IS}
& \multicolumn{2}{|c|}{MG} & \multicolumn{2}{|c|}{LU}\\\cline{3-10}
\multicolumn{2}{|c|}{}  & 2   & 4 & 2 & 4 & 2 & 4 & 2 & 4\\\hline
\multirow{2}*{Run Time(s)}
& IA32 & 24.37   & 16.18 & 19.62 & 8.98 & 31.98 & 18.71 & 622.76 & 266.16\\
& IA64 & 54.41   & 30.29 & 25.54 & 15.72 & 164.16 & 84.73 & 3226.60 & 1723.11\\\hline
\multirow{2}*{Sync Time(ms)}
& IA32 & 7.156   & 25.607 & 189.793 & 70.336 & 286.354 & 86.888 & 6.446 & 18.434\\
& IA64 & 5.960   & 7.043 & 21.980 & 10.078 & 2.780 & 13.793& 2.922 & 5.385\\\hline
\end{tabular}
\end{document}
