* font

https://q3yi.me/post/5_set_different_font_family_for_sc_in_emacs/

https://emacs-china.org/t/emacs/15676/10

** 字体存放位置

/usr/share/fonts
/usr/local/share/fonts

远程ssh 家中的linux

** nerd fonts

https://github.com/ryanoasis/nerd-fonts

安装大量的nerd fonts

** Iosevka 字体 (好像在nerd fonts中已经有了)

使用 Iosevka 字体： https://github.com/be5invis/Iosevka

https://github.com/be5invis/Sarasa-Gothic

https://mirrors.tuna.tsinghua.edu.cn/github-release/be5invis/Iosevka/LatestRelease/

** Sarasa-Gothic字体 更纱黑体

https://mirrors.tuna.tsinghua.edu.cn/github-release/be5invis/Sarasa-Gothic/LatestRelease/


#+BEING_SRC lisp
(set-face-attribute 'default nil :height 260)

#+END_SRC

** 安装后刷新

#+BEING_SRC lisp
noto-fonts-cjk adobe-source-han-sans-cn-font adobe-source-han-serif-cn-fonts

sudo fc-cache
#+END_SRC
刷新记录

** ttf ttf otf

三者都是字体文件格式，跟我们的工作生活都息息相关，以至于我们感觉不到它们的存在，本文对它们做一个简单的说明和对比。

TTF(TrueType Font)是Apple公司和Microsoft公司共同推出的字体文件格式，随着windows的流行，它已经变成最常用的一种字体文件表示方式，TrueType 会逐渐被OpenType 取代；OTF(OpenType Font)是 TTF 的升级版，它采用的是 PostScript 曲线，支持 OpenType 高级特性的更高级字体。


TTC全称是TrueType Collection，它是TrueType字体集成文件(.ttc文件)，是在一单独文件结构中包含多种字体，以便更有效地共享轮廓数据，当多种字体共享同一笔画时，TTC技术可有效地减小字体文件的大小。TTC的字体只有一些常用的汉字，而许多不常用的汉字就没有(选择字体以后依然以宋体显示)。TTC就是几个TTF合成的字库，安装后字体列表中会看到两个以上的字体。两个字体中大部分字都一样时，可以将两种字体做成一个TTC文件，常见的TTC字体，因为共享笔划数据，所以大多这个集合中的字体区别只是字符宽度不一样，以便适应不同的版面排版要求；而TTF字体则只包含一种字型。

虽然都是字体文件，但.ttc是microsoft开发的新一代字体格式标准，可以使多种truetype字体共享同一笔划信息，有效地节省了字体文件所占空间，增加了共享性。但是有些软件缺乏对这种格式字体的识别，使得ttc字体的编辑产生困难。

TTF 扩展名的 O 图标的表示 OpenType - TrueType 字体，采用的是 TrueType 曲线，不过支持 OpenType 的高级特性。

TTF 扩展名的 T 图标的表示 TrueType 字体，采用的是 TrueType 曲线，不支持 OpenType 特性。

OTF 扩展名的 O 图标的表示 OpenType - PostScript 字体，采用的是 PostScript 曲线，支持 OpenType 高级特性。
