* latex

** distibution

Latex workspace

  - MiKTex (windows PC)

  - MacTeX (Mac OS)

所谓 TeX 发行，也叫 TeX 发行版、TeX 系统或者 TeX 套装，指的是包括 TeX 系统的各种可执行程序，以及他们执行时需要的一些辅助程序和宏包文档的集合。

Editors

  - TeXworks （简单易用）

  - TexMaker （功能完备）

** 排版工具

TeXworks 为我们预设了若干排版工具（pdfTeX, pdfLaTeX, XeTeX, XeLaTeX 等），他们分别代表什么实在太过复杂并且也不是当前需要讲明白的。本文中需要用到的排版工具主要是 XeLaTeX，关于这些工具的介绍，可以参看后文。当你对 TeX 系统相当熟悉之后，也可以不适用 TeXworks 预设的工具，自己配置排版工具。

TeXworks 默认的排版工具是 pdfLaTeX，如果你希望更改这个默认值，可以在编辑 - 首选项 - 排版 - 处理工具 - 默认 中修改。

XeLaTeX是中国排版的首要工具

** 入门文档

  - 一份其实很短的 LaTeX 入门文档 https://liam.page/2014/09/08/latex-introduction/


** 规则

  - 注释 %



Environments of any kind1. The only requirement is that the ‘\begin’ statement appears on a new line, preceded by only whitespace.

Text within the usual LaTeX math delimiters. To avoid conflicts with currency specifications, single ‘$’ characters are only recognized as math delimiters if the enclosed text contains at most two line breaks, is directly attached to the ‘$’ characters with no whitespace in between, and if the closing ‘$’ is followed by whitespace, punctuation or a dash. For the other delimiters, there is no such restriction, so when in doubt, use ‘\(...\)’ as inline math delimiters.


#+BEGIN_LATEX
\begin{maxima}
f: x/(x^3-3*x+2),     /* Integrating it */
tex('integrate(f,x)), /* will show its integral... */
print("="),
tex(integrate(f,x)),  /* ...and the result */
print("+K")
\end{maxima}
#+END_LATEX
